#include "nlsr-overhead-app.hpp"
#include "ns3/ptr.h"
#include "ns3/log.h"
#include "ns3/simulator.h"
#include "ns3/packet.h"
#include "ns3/callback.h"
#include "ns3/string.h"
#include "ns3/boolean.h"
#include "ns3/uinteger.h"
#include "ns3/double.h"
#include "ns3/ndnSIM/ndn-cxx/util/random.hpp"

NS_LOG_COMPONENT_DEFINE("NlsrOverheadApp");

namespace ns3 {
namespace ndn {

NS_OBJECT_ENSURE_REGISTERED(NlsrOverheadApp);

TypeId
NlsrOverheadApp::GetTypeId()
{
    static TypeId tid = TypeId("ns3::ndn::NlsrOverheadApp")
        .SetParent<App>()
        .AddConstructor<NlsrOverheadApp>()
        .AddAttribute("LsaInterval", "LSA broadcast interval",
                      TimeValue(Seconds(30.0)),
                      MakeTimeAccessor(&NlsrOverheadApp::m_lsaInterval),
                      MakeTimeChecker())
        .AddAttribute("NodeId", "Node ID for LSA naming",
                      UintegerValue(0),
                      MakeUintegerAccessor(&NlsrOverheadApp::m_nodeId),
                      MakeUintegerChecker<uint32_t>())
        .AddAttribute("Prefixes", "Number of prefixes advertised (for size calc)",
                      UintegerValue(10),
                      MakeUintegerAccessor(&NlsrOverheadApp::m_prefixes),
                      MakeUintegerChecker<uint32_t>())
        .AddAttribute("FixedHeader", "Fixed header size for LSA",
                      UintegerValue(64),
                      MakeUintegerAccessor(&NlsrOverheadApp::m_fixedHeader),
                      MakeUintegerChecker<uint32_t>());
    return tid;
}

NlsrOverheadApp::NlsrOverheadApp()
    : m_nodeId(0)
    , m_prefixes(10)
    , m_fixedHeader(64)
    , m_seqNo(0)
{
    m_seqRng = CreateObject<UniformRandomVariable>();
}

NlsrOverheadApp::~NlsrOverheadApp()
{
}

void
NlsrOverheadApp::StartApplication()
{
    App::StartApplication();
    
    // Desynchronize start
    double jitter = m_seqRng->GetValue(0.0, 1.0);
    m_sendEvent = Simulator::Schedule(Seconds(jitter), &NlsrOverheadApp::SendLsaInterest, this);
}

void
NlsrOverheadApp::StopApplication()
{
    if (m_sendEvent.IsRunning()) {
        m_sendEvent.Cancel();
    }
    App::StopApplication();
}

void
NlsrOverheadApp::SendLsaInterest()
{
    // Name: /local-hop/nlsr/lsa/<NodeID>/<SeqNo>
    Name name("/local-hop/nlsr/lsa");
    name.append(std::to_string(m_nodeId));
    name.appendNumber(m_seqNo++);
    
    auto interest = std::make_shared<Interest>(name);
    interest->setCanBePrefix(false);
    interest->setMustBeFresh(true);
    interest->setNonce(m_seqRng->GetInteger());
    interest->setInterestLifetime(ndn::time::milliseconds(1000)); // 1s
    
    // Simulate size: ApplicationParameters
    // Size = FixedHeader + (NumPrefixes * 4)
    uint32_t payloadSize = m_fixedHeader + (m_prefixes * 4);
    
    // Create Dummy Content
    std::vector<uint8_t> dummyContent(payloadSize, 0xAA);
    auto params = std::make_shared<::ndn::Buffer>(dummyContent.begin(), dummyContent.end());
    interest->setApplicationParameters(params);
    
    // Append ParamsDigest (automatically done by setApplicationParameters in recent ndn-cxx, 
    // but just in case for simulation consistency if required by forwarding)
    // ndnSIM 2.8+ typically handles this.
    
    // NS_LOG_UNCOND("Sending LSA Overhead: " << name << " Size=" << payloadSize);
    
    m_transmittedInterests(interest, this, m_face);
    m_appLink->onReceiveInterest(*interest);
    
    // Update Global Counter (Simulating bytes generated into the network)
    // Note: This is *generated* traffic. Total network load = Generated * Hops.
    // For scalability graph, measuring generated * (N-1) is a reasonable proxy for flooding cost.
    // Standard LS overhead is O(N^2) total messages.
    // Here we count generated bytes.
    // We need a static counter.
    
    m_sendEvent = Simulator::Schedule(m_lsaInterval, &NlsrOverheadApp::SendLsaInterest, this);
}

} // namespace ndn
} // namespace ns3
